SELECT COUNT(*) FROM Data WHERE ID > 7 AND ID < 20;
SELECT COUNT(*) FROM Data WHERE ID > 20 AND ID < 900;
SELECT COUNT(*) FROM Data WHERE ID > 30 AND ID < 3780;
SELECT COUNT(*) FROM Data WHERE ID > 40 AND ID < 470;
SELECT COUNT(*) FROM Data WHERE ID > 50 AND ID < 4460;
SELECT COUNT(*) FROM Data WHERE ID > 60;
SELECT COUNT(*) FROM Data WHERE ID > 70 AND ID < 200;
SELECT COUNT(*) FROM Data WHERE ID > 80 AND ID < 1000;
SELECT COUNT(*) FROM Data WHERE ID > 90 AND ID < 5;
SELECT COUNT(*) FROM Data WHERE ID > 50 AND ID < 20;

